import { PlayerModel } from './player-model'

export const PLAYER: PlayerModel[] = [
  { EntityId: 42, Online: true, PlayerName: "Blackbird 87", Origin: 1, FactionId: 12, SteamId: "sdkjfhkasjdhfkjsdh", Playfield:"Phillipos" },
  { EntityId: 43, Online: true, PlayerName: "ASTIC", Origin: 1, FactionId: 42, SteamId: "ST42", Playfield: "Jeissine"  },
  { EntityId: 44, PlayerName: "Senomega", Origin: 1, FactionId: 43, SteamId: "sdkjfhkasjdhfkjsdh2", Playfield: "Malladis Eta Station"  },
  { EntityId: 45, Online: true, PlayerName: "Hugo", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh3", Playfield: "Mukund Moon"  },
  { EntityId: 46, PlayerName: "Anke", Origin: 1, FactionId: 44, SteamId: "sdkjfhkasjdhfkjsdh4", Playfield: "Mustin"  },
  { EntityId: 42, PlayerName: "Blackbird 87", Origin: 1, FactionId: 12, SteamId: "sdkjfhkasjdhfkjsdh", Playfield: "Phillipos" },
  { EntityId: 43, PlayerName: "ASTIC", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh1", Playfield: "Jeissine" },
  { EntityId: 44, Online: true, PlayerName: "Senomega", Origin: 1, FactionId: 43, SteamId: "sdkjfhkasjdhfkjsdh2", Playfield: "Malladis Eta Station" },
  { EntityId: 45, PlayerName: "Hugo", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh3", Playfield: "Mukund Moon" },
  { EntityId: 46, PlayerName: "Anke", Origin: 1, FactionId: 44, SteamId: "sdkjfhkasjdhfkjsdh4", Playfield: "Mustin" },
  { EntityId: 42, PlayerName: "Blackbird 87", Origin: 1, FactionId: 12, SteamId: "sdkjfhkasjdhfkjsdh", Playfield: "Phillipos" },
  { EntityId: 43, PlayerName: "ASTIC", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh1", Playfield: "Jeissine" },
  { EntityId: 44, PlayerName: "Senomega", Origin: 1, FactionId: 43, SteamId: "sdkjfhkasjdhfkjsdh2", Playfield: "Malladis Eta Station" },
  { EntityId: 45, Online: true, PlayerName: "Hugo", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh3", Playfield: "Mukund Moon" },
  { EntityId: 46, PlayerName: "Anke", Origin: 1, FactionId: 44, SteamId: "sdkjfhkasjdhfkjsdh4", Playfield: "Mustin" },
  { EntityId: 42, PlayerName: "Blackbird 87", Origin: 1, FactionId: 12, SteamId: "sdkjfhkasjdhfkjsdh", Playfield: "Phillipos" },
  { EntityId: 43, PlayerName: "ASTIC", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh1", Playfield: "Jeissine" },
  { EntityId: 44, PlayerName: "Senomega", Origin: 1, FactionId: 43, SteamId: "sdkjfhkasjdhfkjsdh2", Playfield: "Malladis Eta Station" },
  { EntityId: 45, PlayerName: "Hugo", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh3", Playfield: "Mukund Moon" },
  { EntityId: 46, Online: true, PlayerName: "Anke", Origin: 1, FactionId: 44, SteamId: "sdkjfhkasjdhfkjsdh4", Playfield: "Mustin" },
  { EntityId: 42, PlayerName: "Blackbird 87", Origin: 1, FactionId: 12, SteamId: "sdkjfhkasjdhfkjsdh", Playfield: "Phillipos" },
  { EntityId: 43, PlayerName: "ASTIC", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh1", Playfield: "Jeissine" },
  { EntityId: 44, PlayerName: "Senomega", Origin: 1, FactionId: 43, SteamId: "sdkjfhkasjdhfkjsdh2", Playfield: "Malladis Eta Station" },
  { EntityId: 45, PlayerName: "Hugo", Origin: 1, FactionId: 42, SteamId: "sdkjfhkasjdhfkjsdh3", Playfield: "Mukund Moon" },
  { EntityId: 46, PlayerName: "Anke", Origin: 1, FactionId: 44, SteamId: "sdkjfhkasjdhfkjsdh4", Playfield: "Mustin" },
];
