"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PLAYER = [
    { entityId: 42, online: true, playerName: "Blackbird 87", origin: 1, factionId: 12, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh", playfield: "Phillipos" },
    { entityId: 43, online: true, playerName: "ASTIC", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "ST42", playfield: "Jeissine" },
    { entityId: 44, playerName: "Senomega", origin: 1, factionId: 43, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh2", playfield: "Malladis Eta Station" },
    { entityId: 45, online: true, playerName: "Hugo", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh3", playfield: "Mukund Moon" },
    { entityId: 46, playerName: "Anke", origin: 1, factionId: 44, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh4", playfield: "Mustin" },
    { entityId: 42, playerName: "Blackbird 87", origin: 1, factionId: 12, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh", playfield: "Phillipos" },
    { entityId: 43, playerName: "ASTIC", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh1", playfield: "Jeissine" },
    { entityId: 44, online: true, playerName: "Senomega", origin: 1, factionId: 43, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh2", playfield: "Malladis Eta Station" },
    { entityId: 45, playerName: "Hugo", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh3", playfield: "Mukund Moon" },
    { entityId: 46, playerName: "Anke", origin: 1, factionId: 44, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh4", playfield: "Mustin" },
    { entityId: 42, playerName: "Blackbird 87", origin: 1, factionId: 12, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh", playfield: "Phillipos" },
    { entityId: 43, playerName: "ASTIC", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh1", playfield: "Jeissine" },
    { entityId: 44, playerName: "Senomega", origin: 1, factionId: 43, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh2", playfield: "Malladis Eta Station" },
    { entityId: 45, online: true, playerName: "Hugo", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh3", playfield: "Mukund Moon" },
    { entityId: 46, playerName: "Anke", origin: 1, factionId: 44, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh4", playfield: "Mustin" },
    { entityId: 42, playerName: "Blackbird 87", origin: 1, factionId: 12, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh", playfield: "Phillipos" },
    { entityId: 43, playerName: "ASTIC", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh1", playfield: "Jeissine" },
    { entityId: 44, playerName: "Senomega", origin: 1, factionId: 43, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh2", playfield: "Malladis Eta Station" },
    { entityId: 45, playerName: "Hugo", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh3", playfield: "Mukund Moon" },
    { entityId: 46, online: true, playerName: "Anke", origin: 1, factionId: 44, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh4", playfield: "Mustin" },
    { entityId: 42, playerName: "Blackbird 87", origin: 1, factionId: 12, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh", playfield: "Phillipos" },
    { entityId: 43, playerName: "ASTIC", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh1", playfield: "Jeissine" },
    { entityId: 44, playerName: "Senomega", origin: 1, factionId: 43, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh2", playfield: "Malladis Eta Station" },
    { entityId: 45, playerName: "Hugo", origin: 1, factionId: 42, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh3", playfield: "Mukund Moon" },
    { entityId: 46, playerName: "Anke", origin: 1, factionId: 44, pos: { x: 1, y: 2, z: 3 }, steamId: "sdkjfhkasjdhfkjsdh4", playfield: "Mustin" },
];
//# sourceMappingURL=player-mock.js.map