// <auto-generated />
using EmpyrionModWebHost.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpyrionModWebHost.Migrations.Faction
{
    [DbContext(typeof(FactionContext))]
    partial class FactionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EmpyrionModWebHost.Models.Faction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abbrev");

                    b.Property<int>("FactionId");

                    b.Property<string>("Name");

                    b.Property<byte>("Origin");

                    b.HasKey("Id");

                    b.ToTable("Factions");
                });
#pragma warning restore 612, 618
        }
    }
}
