// <auto-generated />
using System;
using EmpyrionModWebHost.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpyrionModWebHost.Migrations.FactoryItems
{
    [DbContext(typeof(FactoryItemsContext))]
    partial class FactoryItemsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EmpyrionModWebHost.Models.FactoryItems", b =>
                {
                    b.Property<string>("Id");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("Content");

                    b.Property<string>("InProduction");

                    b.Property<string>("Produced");

                    b.HasKey("Id", "Timestamp");

                    b.ToTable("FactoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
